const GAME_CONFIG = {
  adminPassword: process.env.ADMIN_PASSWORD || 'admin123',
  port: process.env.PORT || 3000,
  maxPlayers: 7,
  minPlayers: 2,
  totalRounds: 11,
  votingRounds: [2, 4, 6, 8, 10],
  answerTimeFirstTurn: 35,
  answerTime: 25,
  battlePrepTime: 5,
  battleTime: 25,
  revealTime: 4,
  noBattleAnswerTime: 3,
  roundSummaryDelay: 3,
  revealAnswerDelay: 2,
  scoreboardTime: 15,
  votingTime: 90,
  votingResultsTime: 12,
  speechTime: 45,
  finalVotingTime: 45,
  catchThreshold: 3,
  correctVotePoints: 500,
  wrongAccusationPenalty: 500,
  hiddenLiarReward: 700,
  liarCaughtPenaltyFraction: 0.5,
  powerupMultiplier: 2,
  forbiddenWords: ['cwel', 'nigger', 'czarnuch'],
  validQuestionSets: ['set1', 'set2', 'set3', 'set4', 'set5', 'test']
};

module.exports = { GAME_CONFIG };
